export const DEFAULT_CREATOR_COMMUNITY_NAME = 'My Community';
export const CREATOR_PREVIEW_MESSAGE_LIMIT = 1900;
export const CREATOR_APPLY_PREVIEW_MESSAGE_LIMIT = 1500;
export const CREATOR_APPLY_CONFIRMATION_TTL_MS = 5 * 60 * 1000;
